import type { Metadata } from "next";
import {
  Poppins,
  Inter,
  Space_Grotesk,
  Outfit,
} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Gradient from "./components/Gradient";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["200", "400", "600"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["300", "400", "500"],
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-spaceGrotesk",
  weight: ["300", "400", "500", "600", "700"],
});

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} ${spaceGrotesk.variable} ${outfit.variable} antialiased bg-black overflow-y-scroll`}
        style={{ scrollbarGutter: "stable" }}
      >
        <Navbar />
        <div className="relative z-0 pt-16 px-4 sm:px-6 lg:px-8">
          {children}
        </div>
      </body>
    </html>
  );
}
